name: flow_up
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  theme_provider: ^0.5.0
  cupertino_icons: ^1.0.6
  just_audio: ^0.9.36
  audio_video_progress_bar: ^2.0.1
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.0
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/